#!/usr/bin/env bash
# writ-export-checks.sh - Export writ.json criteria as a runnable CI check script
#
# Usage: ./scripts/writ-export-checks.sh [writ.json]
#
# Reads writ.json and emits a self-contained bash script (to stdout) that
# evaluates all acceptance criteria for completed features. Pipe to a file
# and run in CI, or execute directly:
#
#   ./scripts/writ-export-checks.sh > ci-checks.sh && bash ci-checks.sh
#   bash <(./scripts/writ-export-checks.sh)
#
# Only completed features are included - CI verifies regressions, not pending work.
# All 6 Writ criterion types are supported (same logic as writ-verify).

set -euo pipefail

SPEC="${1:-writ.json}"

if [ ! -f "$SPEC" ]; then
  echo "Error: writ.json not found at '$SPEC'" >&2
  echo "Usage: $0 [path/to/writ.json]" >&2
  exit 1
fi

python3 - "$SPEC" <<'PYTHON'
import json, sys, os

spec_file = sys.argv[1]

with open(spec_file) as f:
    spec = json.load(f)

completed = [f for f in spec.get("features", []) if f.get("status") == "completed"]

if not completed:
    print("#!/usr/bin/env bash")
    print("# Auto-generated by writ-export-checks.sh")
    print(f"# Source: {spec_file}")
    print("echo 'No completed features found in writ.json.'")
    print("exit 0")
    sys.exit(0)

# Detect runtime dependencies from command_succeeds and test_passes criteria
runtimes = set()
for feature in completed:
    for c in feature.get("acceptance_criteria", []):
        if c["type"] in ("command_succeeds", "test_passes"):
            t = c["target"]
            if "node " in t or "npm " in t or "npx " in t:
                runtimes.add("node")
            if "python" in t or "pytest" in t or "ruff" in t:
                runtimes.add("python3")
            if "cargo" in t or "rustc" in t:
                runtimes.add("cargo (Rust)")
            if "go " in t or "go build" in t or "go test" in t:
                runtimes.add("go")
            if "jq " in t:
                runtimes.add("jq")

print("#!/usr/bin/env bash")
print("# Auto-generated by writ-export-checks.sh - do not edit manually.")
print(f"# Source: {spec_file}")
print(f"# Project: {spec.get('project', 'unknown')}")
print(f"# Features checked: {len(completed)} completed")
if runtimes:
    print(f"# Runtime dependencies detected: {', '.join(sorted(runtimes))}")
print("#")
print("# Run this script in the project root. Exit code 0 = all pass.")
print()
print("set -uo pipefail")
print()
print("PASS=0")
print("FAIL=0")
print("SKIP=0")
print()

KNOWN_TYPES = {"file_exists", "file_contains", "command_succeeds", "test_passes", "grep_match", "json_path_check"}

for feature in completed:
    fid = feature["id"]
    title = feature["title"]
    criteria = feature.get("acceptance_criteria", [])
    if not criteria:
        continue

    print(f'echo ""')
    print(f'echo "=== {fid}: {title} ==="')

    for i, c in enumerate(criteria):
        ctype = c.get("type", "")
        target = c.get("target", "")
        expected = c.get("expected", "")
        desc = c.get("description", f"criterion {i+1}")

        # Escape for shell use in echo
        safe_desc = desc.replace("'", "'\\''")

        if ctype not in KNOWN_TYPES:
            print(f"echo '  SKIP (unknown type: {ctype}): {safe_desc}'")
            print("SKIP=$((SKIP+1))")
            continue

        if ctype == "file_exists":
            cmd = f'test -f "{target}"'
        elif ctype == "file_contains":
            safe_exp = expected.replace("'", "'\\''")
            cmd = f"grep -qF '{safe_exp}' '{target}'"
        elif ctype in ("command_succeeds", "test_passes"):
            # Emit as-is - user is responsible for environment
            cmd = target
        elif ctype == "grep_match":
            safe_exp = expected.replace("'", "'\\''")
            cmd = f"grep -r '{safe_exp}' {target} > /dev/null 2>&1"
        elif ctype == "json_path_check":
            safe_exp = expected.replace("'", "'\\''")
            safe_target = target.replace("'", "'\\''")
            cmd = f"if command -v jq >/dev/null 2>&1; then jq -e '{safe_exp}' '{safe_target}' > /dev/null 2>&1; else python3 -c \"import json,sys; d=json.load(open('{safe_target}')); sys.exit(0 if d else 1)\" > /dev/null 2>&1; fi"

        print(f"if {cmd}; then")
        print(f"  echo '  PASS: {safe_desc}'")
        print("  PASS=$((PASS+1))")
        print("else")
        print(f"  echo '  FAIL: {safe_desc}'")
        print("  FAIL=$((FAIL+1))")
        print("fi")

print()
print('echo ""')
print('echo "=== Results: $PASS passed, $FAIL failed, $SKIP skipped ==="')
print('if [ "$FAIL" -gt 0 ]; then')
print('  echo "FAILED"')
print('  exit 1')
print('fi')
print('echo "PASSED"')
PYTHON
